version: 2.1

orbs:
  node: circleci/node@7.0.0
  slack: circleci/slack@4.4.4
jobs:
  build_and_deploy_moonbeam:
    resource_class: large
    docker:
      - image: 'cimg/node:16.17.0'
    environment:
      DEPLOY_HOST: 34.53.102.108
      DEPLOY_FOLDER: moonfarm-voltswap-finance
      SSH_OPTIONS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:48o4O3yWCP1MbjxhyGvDL+NNUsYcRJVodZjzg7nV0C4"
      - run:
          name: install rsync
          command: |
            sudo apt-get update 
            sudo apt-get install -y rsync
      - checkout
      - restore_cache:
          key: geyser-moonbeam-deps-{{ checksum "package.json" }}
      - run:
          name: install yarn dependencies
          command: cd frontend && yarn
      - save_cache:
          key: geyser-moonbeam-deps-{{ checksum "package.json" }}
          paths:
            - frontend/node_modules
      - run:
          name: production build
          command: cd frontend && CI=false NODE_ENV=production SKIP_PREFLIGHT_CHECK=true ESLINT_NO_DEV_ERRORS=true yarn build
          environment:
            NODE_OPTIONS: --max_old_space_size=6144
      - run:
          name: deploy
          command: |
            rsync -e "ssh $SSH_OPTIONS" -rzvh --delete ./frontend/build/ root@$DEPLOY_HOST:/var/www/$DEPLOY_FOLDER/
            ssh $SSH_OPTIONS root@$DEPLOY_HOST "service nginx restart"
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1


workflows:
  fresh_deploy:
    jobs:
      - build_and_deploy_moonbeam:
          context:
            - slack-secrets
          filters:
            tags:
              only: /^v.*/
            branches:
              only: moonbeam
